application: mestairplane
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: latest

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(js|html|css))
  static_files: static/\1
  upload: static/(.*\.(js|html|css))

- url: /pics
  static_dir: pics

- url: /.*
  script: mestairplane.py

builtins:
- remote_api: on
